### ISSUE TITLE
numerical overflow in calculating likelihood

### ISSUE THREAD

**Issue by AlexKram** [chjackson/msm#10] opened 2018-06-09 08:14 UTC
I want to raise this issue once again, since there was no answer

```
> Q <- rbind(c(0, 0.25, 0, 0.25),
           c(0.166, 0, 0.166, 0.166),
           c(0, 0.25, 0, 0.25),
           c(0, 0, 0, 0))
> cavsex.msm <- msm(state ~ years, subject=PTNUM, data=cav, qmatrix=Q, covariates = ~age)
```

```
Error in Ccall.msm(params, do.what = "lik", ...) : 
  numerical overflow in calculating likelihood
```

Why is this not working?

**Comment by chjackson** [comment] 2018-06-10 20:02
Duplicate of #5

**Closed by chjackson** 2018-06-10 20:02 UTC
Labels: duplicate
