### ISSUE TITLE
Questions about using weights in msm package

### ISSUE THREAD

**Issue by ghost** [chjackson/msm#64] opened 2023-01-19 09:13 UTC
Dear Prof. Jackson,

Thank you for providing the msm package! I am a postgraduate social science student. I am using social survey data and the msm package to analyse health state transition probabilities. I would like to apply social science survey weights to the msm package, but am unsure how to apply it. I was wondering if the package has a function to apply the weights, or some other way to handle it! Thanks again for your work!

Best wishes, 

Wanying

**Comment by chjackson** [comment] 2023-01-19 09:15
A way to do this is explained in the answer to https://github.com/chjackson/msm/issues/50 .

**Comment by lingwany98** [comment] 2023-01-19 09:17
> #[50](https://github.com/chjackson/msm/issues/50) 的答案中解释了一种方法。

Thank you very much for your reply!

**Comment by chjackson** [comment] 2023-11-22 14:59
Duplicate of #50

**Comment by chjackson** [comment] 2024-01-31 14:08
Subject-specific weights are now implemented in https://github.com/chjackson/msm/commit/4e1910d1c5f15f4702e21b77a40a236de456bd63 and subsequent commits.

**Closed by chjackson** 2024-01-31 14:08 UTC
