### ISSUE TITLE
MSM with covariate: Error in omit | (nobspt == 1) : non-conformable arrays

### ISSUE THREAD

**Issue by fintzij** [chjackson/msm#30] opened 2020-12-01 02:52 UTC
Hello,

I am trying to fit a multistate model with a covariate and am getting the following error: 

```
Error in omit | (nobspt == 1) : non-conformable arrays
```

Not really sure what in my model setup would lead msm to enter this function, but the error appears to be thrown on line 25 of `na.find.msmdata` and arises from the omit object being a matrix, in my case of dimension 15k x 1, and nobspt being a table. Perhaps this is an R 4.0+ issue and these two objects were previously conformable? 

Thanks,
Jon

**Comment by chjackson** [comment] 2020-12-01 09:54
Hi Jon - could I have a minimal reproducible example that triggers this error, and I'll fix.

**Comment by fintzij** [comment] 2020-12-01 16:00
Hi Chris,

Of course making the MWE would have led me to the problem. Not an issue with msm at all. I was trying to use a centered version of my age variable and was generating it with the scale() function. For some strange reason, I end up with a column in my data frame that is of class "matrix" when I generate the variable in this way. 

Thanks for the swift response, sorry for the trouble!

Cheers,
Jon

**Comment by chjackson** [comment] 2020-12-01 18:03
I'll reopen this as a todo for me, as I'd still consider it a bug.  Instead of giving a nonsense error, msm should have told you the real problem - that a certain column in your data was a matrix and should have been a vector.

**Comment by getnetbogale145** [comment] 2023-07-15 12:26
So how can I fix this probelm? 
> # Fit the MSM model using the qmatrix and crude initial values
> cav.msm <- msm(formula, subject = Subject, data = data, qmatrix = qmatrix, 
+                method = "BFGS", control = list(maxit = 1000000, trace = 1, REPORT = 100, tol = 1e-6),
+                start = Q.crude)
Error in omit | (nobspt == 1) : non-conformable arrays

**Comment by chjackson** [comment] 2023-07-16 08:11
@getnetbogale145 Could you prepare a minimal, reproducible example please.

**Comment by getnetbogale145** [comment] 2023-07-16 08:42
Here is the R code if you can get insight:
> library(msm)
> # Read the dataset
> data <- read.csv("C:/Users/getne/OneDrive/Desktop/Data/3rd Missing Delet Dr Haile/Next/xyz.csv")
> # Convert the state column to a factor with appropriate levels
> data$state <- factor(data$state, levels = c(1, 2, 3, 4, 5, 6, 7, 8))
> # Assuming Subject is a character vector
> data$Subject <- factor(data$Subject)
> # Or, if Subject is already a factor but needs to be re-leveled
> data$Subject <- factor(data$Subject, levels = unique(data$Subject))
> # Calculate the number of transitions between states
> transition_counts <- statetable.msm(state, Subject, data = data)
> transition_counts <- as.matrix(transition_counts)
> transition_counts
    to
from    1    2    3    4    5    6    7    8
   1 2704  152  145  224  174  288    0   41
   2   89   26   10   13   43   84    0   42
   3  329   44  108   18  164   22    0   18
   4  161   11    7   87   11   89    0    4
   5  221   49   92   22  427   93    2  210
   6  194   22   22   73   45  288    4  121
   7    1    1    0    0    1    2    0    0
   8   75   15   29    5  104   67    1  187
> # Convert transition counts to transition probabilities
> transition_probabilities <- transition_counts / rowSums(transition_counts)
> transition_probabilities
    to
from           1           2           3           4           5           6           7
   1 0.725321888 0.040772532 0.038894850 0.060085837 0.046673820 0.077253219 0.000000000
   2 0.289902280 0.084690554 0.032573290 0.042345277 0.140065147 0.273615635 0.000000000
   3 0.467994310 0.062588905 0.153627312 0.025604552 0.233285917 0.031294452 0.000000000
   4 0.435135135 0.029729730 0.018918919 0.235135135 0.029729730 0.240540541 0.000000000
   5 0.198028674 0.043906810 0.082437276 0.019713262 0.382616487 0.083333333 0.001792115
   6 0.252275683 0.028608583 0.028608583 0.094928479 0.058517555 0.374512354 0.005201560
   7 0.200000000 0.200000000 0.000000000 0.000000000 0.200000000 0.400000000 0.000000000
   8 0.155279503 0.031055901 0.060041408 0.010351967 0.215320911 0.138716356 0.002070393
    to
from           8
   1 0.010997854
   2 0.136807818
   3 0.025604552
   4 0.010810811
   5 0.188172043
   6 0.157347204
   7 0.000000000
   8 0.387163561
> # Create a vector of initial values
> initial_values <- as.vector(t(transition_probabilities))
> # Create an empty 8x8 qmatrix
> qmatrix <- matrix(0, nrow = 8, ncol = 8)
> # Fill in the qmatrix using the initial values
> for (i in 1:8) {
+   start_index <- (i - 1) * 8 + 1
+   end_index <- i * 8
+   qmatrix[i, ] <- initial_values[start_index:end_index]
+ }
> initial_values
 [1] 0.725321888 0.040772532 0.038894850 0.060085837 0.046673820 0.077253219 0.000000000
 [8] 0.010997854 0.289902280 0.084690554 0.032573290 0.042345277 0.140065147 0.273615635
[15] 0.000000000 0.136807818 0.467994310 0.062588905 0.153627312 0.025604552 0.233285917
[22] 0.031294452 0.000000000 0.025604552 0.435135135 0.029729730 0.018918919 0.235135135
[29] 0.029729730 0.240540541 0.000000000 0.010810811 0.198028674 0.043906810 0.082437276
[36] 0.019713262 0.382616487 0.083333333 0.001792115 0.188172043 0.252275683 0.028608583
[43] 0.028608583 0.094928479 0.058517555 0.374512354 0.005201560 0.157347204 0.200000000
[50] 0.200000000 0.000000000 0.000000000 0.200000000 0.400000000 0.000000000 0.000000000
[57] 0.155279503 0.031055901 0.060041408 0.010351967 0.215320911 0.138716356 0.002070393
[64] 0.387163561
> # Apply the constraint: each row of the qmatrix should sum to 1
> qmatrix <- t(t(qmatrix) / rowSums(qmatrix))
> qmatrix
          [,1]       [,2]       [,3]       [,4]       [,5]       [,6]        [,7]       [,8]
[1,] 0.7253219 0.04077253 0.03889485 0.06008584 0.04667382 0.07725322 0.000000000 0.01099785
[2,] 0.2899023 0.08469055 0.03257329 0.04234528 0.14006515 0.27361564 0.000000000 0.13680782
[3,] 0.4679943 0.06258890 0.15362731 0.02560455 0.23328592 0.03129445 0.000000000 0.02560455
[4,] 0.4351351 0.02972973 0.01891892 0.23513514 0.02972973 0.24054054 0.000000000 0.01081081
[5,] 0.1980287 0.04390681 0.08243728 0.01971326 0.38261649 0.08333333 0.001792115 0.18817204
[6,] 0.2522757 0.02860858 0.02860858 0.09492848 0.05851756 0.37451235 0.005201560 0.15734720
[7,] 0.2000000 0.20000000 0.00000000 0.00000000 0.20000000 0.40000000 0.000000000 0.00000000
[8,] 0.1552795 0.03105590 0.06004141 0.01035197 0.21532091 0.13871636 0.002070393 0.38716356
> # Define the formula for the model
> formula <- state ~ Time + Region + Residence + ch_sex + ch_age_mon + BMI + hh_size + Wealth_index +
+   Housing_Quality_Index + Access_to_services_index + Consumer_durables_index +
+   Access_to_safe_drinking_water + toiletq_new + Access_to_electricity + cookingq_new
> # Normalize the covariates
> data$Time <- scale(data$Time)
> data$BMI <- scale(data$BMI)
> data$hh_size <- scale(data$hh_size)
> data$Wealth_index <- scale(data$Wealth_index)
> data$Housing_Quality_Index <- scale(data$Housing_Quality_Index)
> data$Access_to_services_index <- scale(data$Access_to_services_index)
> data$Consumer_durables_index <- scale(data$Consumer_durables_index)
> # Compute crude initial values for the qmatrix
> Q.crude <- crudeinits.msm(formula, Subject, data = data, qmatrix = qmatrix)
> Q.crude
           [,1]        [,2]        [,3]        [,4]        [,5]        [,6]         [,7]
[1,] -0.3856011  0.05723767  0.05460172  0.08435025  0.06552207  0.10845032  0.000000000
[2,]  0.4059109 -1.28158382  0.04560797  0.05929035  0.19611425  0.38310691  0.000000000
[3,]  0.6506177  0.08701270 -1.17664901  0.03559610  0.32432006  0.04350635  0.000000000
[4,]  0.6052992  0.04135585  0.02631736 -1.06397313  0.04135585  0.33460639  0.000000000
[5,]  0.2759795  0.06119001  0.11488737  0.02747307 -0.86040653  0.11613615  0.002497552
[6,]  0.3642679  0.04130873  0.04130873  0.13706986  0.08449512 -0.90315896  0.007510677
[7,]  0.3089940  0.30899396  0.00000000  0.00000000  0.30899396  0.61798793 -1.544969820
[8,]  0.2249956  0.04499912  0.08699830  0.01499971  0.31199391  0.20099607  0.002999941
            [,8]
[1,]  0.01543911
[2,]  0.19155345
[3,]  0.03559610
[4,]  0.01503849
[5,]  0.26224292
[6,]  0.22719799
[7,]  0.00000000
[8,] -0.88798265
> # Fit the MSM model using the qmatrix and crude initial values
> cav.msm <- msm(formula, subject = Subject, data = data, qmatrix = qmatrix, 
+                method = "Nelder-Mead", control = list(maxit = 1000000, trace = 1, REPORT = 100, tol = 1e-6),
+                start = Q.crude)
Error in omit | (nobspt == 1) : non-conformable arrays

I don't know what is the problem.

**Comment by chjackson** [comment] 2023-07-16 12:03
@getnetbogale That's not reproducible, because I can't see the data.  It doesn't look minimal either. 

However I can see that your `formula` argument to `msm` contains things that it shouldn't.  This should not be a regression formula - the right hand side should just contain the time variable.  Read the documentation a bit more carefully - covariates should usually go in the `covariates` argument.

**Comment by getnetbogale145** [comment] 2023-07-16 13:14
thank you megatime @chjackson. Can you read my inuery in detail as follows:
I am currently working on a Markov Chain model to analyze child undernutrition. The title of my paper is "Analyzing the Dynamics of Child Undernutrition in Ethiopia: A Multi-State Markov Chain Model Approach."

My dataset consists of four states: underweight, stunting, thinness, and normal. Each child can be in more than one state simultaneously (represented as binary outcomes: 0 for No and 1 for Yes). If a child is not underweight, stunted, or experiencing thinness, they are considered normal. To determine the normal states, I calculate them based on the remaining three states. If a child is not underweight, stunted, or experiencing thinness, their normal state is set to 0. If they are in at least one of these states, their normal state is set to 1. 

Therefore, my dataset includes columns for underweight, stunting, thinness, and normal as state values. Additionally, it contains the variables Time and Subject. Here is a list of the variables in the dataset along with their labels, variable types, and variable categories:

Variable Name Label Variable Type Variable Category
Observation Observation
Subject Subject ID
Time Round of Survey
underweight Low weight for age
stunting Short height for age
thinness Low BMI for age
normal Normal from all states
Region Region of residence Time-invariant Categorical
Residence Area of residence (urban/rural) Time-invariant Categorical
ch_sex Child's sex Time-invariant Categorical
ch_age_mon Child's age (in months) Time-variant Continuous
BMI Calculated BMI = weight/squared(height) Time-variant Continuous
hh_size Household size Time-variant Continuous
Wealth_index Wealth index Time-variant Continuous
Housing_Quality_Index Housing Quality Index Time-variant Continuous
Access_to_services_index Access to services index Time-variant Continuous
Consumer_durables_index Consumer durables index Time-variant Continuous
Access_to_safe_drinking_water Access to safe drinking water Time-variant Categorical
toiletq_new Access to sanitation (toilet?) Time-variant Categorical
Access_to_electricity Access to electricity Time-variant Categorical
cookingq_new Access to adequate fuels for cooking Time-variant Categorical

I make effort to build the Multi-State Markov Chain model for the last 3 weeks. Still I cann't. Can you help me?

**Comment by getnetbogale145** [comment] 2023-07-16 13:51
I update the msm function:
> # Fit the MSM model using the qmatrix and crude initial values
> cav.msm <- msm(state ~ Time, subject = Subject, data = data, qmatrix = qmatrix, 
+                method = "Nelder-Mead", control = list(maxit = 1000000, trace = 1, REPORT = 100, tol = 1e-6),
+                start = as.vector(initial_values), covariates = ~ Region + Residence + ch_sex + ch_age_mon + BMI + hh_size + 
+                  Wealth_index + Housing_Quality_Index + Access_to_services_index + 
+                  Consumer_durables_index)
Error in omit | (nobspt == 1) : non-conformable arrays

**Comment by getnetbogale145** [comment] 2023-07-16 13:52
I update the msm function as follows:
> # Fit the MSM model using the qmatrix and crude initial values
> cav.msm <- msm(state ~ Time, subject = Subject, data = data, qmatrix = qmatrix, 
+                method = "Nelder-Mead", control = list(maxit = 1000000, trace = 1, REPORT = 100, tol = 1e-6),
+                start = as.vector(initial_values), covariates = ~ Region + Residence + ch_sex + ch_age_mon + BMI + hh_size + 
+                  Wealth_index + Housing_Quality_Index + Access_to_services_index + 
+                  Consumer_durables_index)
Error in omit | (nobspt == 1) : non-conformable arrays

**Comment by chjackson** [comment] 2023-07-16 15:04
@getnetbogale145 As I have said, I cannot help if you don't supply the data needed for me to reproduce the problem.  Have you checked whether any columns of your data frame are matrices rather than vectors, as reported above in this thread at https://github.com/chjackson/msm/issues/30#issuecomment-736646596

**Comment by getnetbogale145** [comment] 2023-07-16 17:49
thank you.

**Comment by chjackson** [comment] 2023-11-22 19:25
Fixed in https://github.com/chjackson/msm/commit/47a6a1afaf48ca5bec5f6b473108db902cb145dc I think

**Closed by chjackson** 2023-11-22 19:25 UTC
